#!/usr/bin/env python3
"""Regenerate the landing page's shelf data from catalog.tsv and features.tsv.

Three blocks, because the page needs three different things.

SHELF is the shelf itself, off the S rows tools/discover.py writes: every
release of all four engines, as id, published label and date. Chromium is in
here with the other three - it used not to be, and the page then listed the
twenty-one curated milestones while the hero above it counted all 288, so the
engine tabs added up to 217 and the manager and the page disagreed about how
many Chromium versions exist.

SEED is the editorial layer over Chromium: full version, snapshot revision, host
platform and the hand-written note, for the milestones catalog.tsv has a V row
for. The page merges it over SHELF's Chromium rows. It also resolves newly
released milestones itself at runtime, so this is not what keeps that shelf
current - it keeps the *first paint* current, before any fetch has come back.

NOTES is the changelog, off features.tsv, keyed exactly the way the manager keys
it. Without it the page had a note for twenty-one Chromium milestones and a
release date for everything else, while the manager shows what every version was
first to support - the same complaint, in a different window.

There is no runtime top-up for anything but Chromium: Mozilla's index,
Microsoft's enterprise feed and Playwright's release list are all fetched
server-side by discover.py and none of them answer a browser (no CORS). So the
shelf a visitor sees for Firefox, Edge and WebKit is exactly what was catalogued
the last time discover.py ran - which is why this runs after it, not instead
of it.

Nothing else in the page needs syncing: no prose, title, meta or JSON-LD names a
count or a version range, precisely so that none of it can go stale.

    python3 tools/sync-landing.py            # rewrite docs/index.html
    python3 tools/sync-landing.py --check    # report drift, do not write
"""
import argparse
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CATALOG = os.path.join(ROOT, "catalog.tsv")
FEATURES = os.path.join(ROOT, "features.tsv")
PAGE = os.path.join(ROOT, "docs", "index.html")

# Written at the indentation the blocks already sit at inside the page's one
# <script>, so a rewrite shows up as a data diff rather than as the whole file
# moving six columns left.
PAD = " " * 8
SEED_BEGIN = PAD + "/* seed:begin - regenerated by tools/sync-landing.py from catalog.tsv */\n"
SEED_END = PAD + "/* seed:end */"
SHELF_BEGIN = PAD + "/* shelf:begin - regenerated by tools/sync-landing.py from catalog.tsv */\n"
SHELF_END = PAD + "/* shelf:end */"
NOTES_BEGIN = PAD + "/* notes:begin - regenerated by tools/sync-landing.py from features.tsv */\n"
NOTES_END = PAD + "/* notes:end */"

# Chromium first, which is the order the engine tabs are in.
SHELF_ENGINES = ("chromium", "firefox", "edge", "webkit")

# The shelf describes one host - an Apple Silicon Mac - because that is what the
# screenshot above it shows. Everything else on the page is platform-neutral.
NATIVE, ROSETTA = "native arm64", "x86_64 · Rosetta"

# How many feature names travel to the page per release. The file holds up to
# fourteen and the manager's dialog shows all of them, but the card on the page
# has one paragraph to say it in - and six names is what fits before that
# paragraph turns into a list nobody reads. The total count goes along with them,
# so the card can say how much it is not showing.
NOTE_NAMES = 6

# The milestone the scrubber's markup names before any script runs. Its index in
# the Chromium shelf is what aria-valuenow has to be, and that index moved the
# moment the shelf stopped being the curated twenty-one.
STATIC_MILESTONE = "74"


def js(text):
    """Safe inside a single-quoted JS string inside an inline <script>.

    The names are HTML element names among other things, so "<script>" is already
    in there. That one is harmless - only "</script" ends the element - but the
    file is generated from data nobody reviews, so the closing form is escaped
    too rather than trusted to stay absent.
    """
    return (text.replace("\\", "\\\\")
                .replace("'", "\\'")
                .replace("</", "<\\/"))


def read_catalog():
    rows = []
    builds = {}
    shelf = {engine: [] for engine in SHELF_ENGINES}
    seen = set()
    with open(CATALOG) as handle:
        for line in handle:
            if line.startswith("#") or not line.strip():
                continue
            parts = line.rstrip("\n").split("\t")
            if parts[0] == "V":
                rows.append({
                    "milestone": int(parts[1]),
                    "version": parts[2],
                    "note": parts[3] if len(parts) > 3 else "",
                })
            elif parts[0] == "B":
                builds.setdefault(int(parts[1]), {})[parts[2]] = parts[3]
            elif parts[0] == "S" and len(parts) >= 6:
                # Two WebKit builds can carry the same published name, so the id
                # is the identity - and the same id twice is a stale row the
                # rewrite left behind, not a second release.
                key = (parts[1], parts[3])
                if key in seen:
                    continue
                seen.add(key)
                if parts[1] in shelf:
                    shelf[parts[1]].append((parts[3], parts[4], parts[5]))
    for releases in shelf.values():
        releases.sort(key=lambda r: r[2])
    return rows, builds, shelf, len(seen)


def read_features(shelf, entries):
    """What each release was first to support, for the releases on this page.

    Filtered against the shelf rather than shipped whole: features.tsv is 146 KB
    because it carries up to fourteen names per release, and the page wants six
    for releases it actually lists. What is left is a twentieth of the file.
    """
    on_page = {(engine, release[0]) for engine, releases in shelf.items()
               for release in releases}
    on_page |= {("chromium", entry["v"]) for entry in entries}
    found = {}
    try:
        handle = open(FEATURES)
    except OSError:
        print("no features.tsv - run tools/features.py --write", file=sys.stderr)
        return found
    with handle:
        for line in handle:
            parts = line.rstrip("\n").split("\t")
            if len(parts) < 5 or parts[0] != "F":
                continue
            key = (parts[1], parts[2])
            if key not in on_page:
                continue
            names = [name for name in parts[4].split("|") if name][:NOTE_NAMES]
            if not names:
                continue
            found[key] = (parts[3], names)
    return found


def seed_entries(rows, builds):
    """One line per milestone, in the shape the page's SEED array expects."""
    entries = []
    for row in rows:
        available = builds.get(row["milestone"], {})
        revision = available.get("Mac_Arm") or available.get("Mac")
        if not revision:
            continue
        year, _, note = row["note"].partition(". ")
        if not re.fullmatch(r"\d{4}", year):
            year, note = "", row["note"]
        entries.append({
            "v": str(row["milestone"]),
            "full": row["version"],
            "rev": revision,
            "plat": NATIVE if "Mac_Arm" in available else ROSETTA,
            "year": year,
            # The catalog is plain ASCII so it stays diffable; the page is prose.
            "note": js(note.replace(" - ", " — ")),
        })
    return entries


def shelf_block(shelf, total):
    """One line per release, packed: 'id|label|date'.

    The page splits it back apart. A row is three short strings and there are a
    couple of hundred of them; spelt out as objects, one field per line the way
    SEED is, they would add a thousand lines to a file a browser has to parse
    before it can paint anything.
    """
    lines = [SHELF_BEGIN, PAD + "const SHELF = {\n"]
    for engine in SHELF_ENGINES:
        releases = shelf.get(engine) or []
        lines.append(PAD + "  %s: [\n" % engine)
        for release in releases:
            lines.append(PAD + "    '%s|%s|%s',\n" % release)
        lines.append(PAD + "  ],\n")
    lines.append(PAD + "};\n")
    lines.append(PAD + "// The manager prints this same number, so the two must"
                       " come from one place.\n")
    lines.append(PAD + "const SHELF_TOTAL = %d;\n" % total)
    lines.append(SHELF_END)
    return "".join(lines)


def seed_block(entries):
    lines = [SEED_BEGIN, PAD + "const SEED = [\n"]
    for i, e in enumerate(entries):
        comma = "" if i == len(entries) - 1 else ","
        lines.append(
            PAD + "  {{v:'{v}', full:'{full}', rev:'{rev}', plat:'{plat}', "
            "year:'{year}', note:'{note}'}}{comma}\n".format(comma=comma, **e)
        )
    lines.append(PAD + "];\n")
    lines.append(SEED_END)
    return "".join(lines)


def notes_block(features):
    """'<engine>:<id>' -> '<total>|<name>|<name>|...', the manager's own keying.

    Packed the way SHELF is and for the same reason: 260 entries as objects with
    a names array each is a thousand lines of JavaScript to parse before the
    first paint, for two fields.
    """
    lines = [NOTES_BEGIN]
    lines.append(PAD + "// What each release was first to support, off the same"
                       " features.tsv the\n")
    lines.append(PAD + "// manager reads, keyed the same way: \"<engine>:<id>\""
                       " -> \"<total>|<name>|...\".\n")
    lines.append(PAD + "// Trimmed to the %d most notable names, which is what"
                       " one line of the card\n" % NOTE_NAMES)
    lines.append(PAD + "// holds; the total rides along so the card can say how"
                       " much it is not showing.\n")
    lines.append(PAD + "const NOTES = {\n")
    for engine in SHELF_ENGINES:
        for (found_engine, ident), (count, names) in sorted(features.items()):
            if found_engine != engine:
                continue
            lines.append(PAD + "  '%s:%s': '%s|%s',\n"
                         % (engine, ident, count, js("|".join(names))))
    lines.append(PAD + "};\n")
    lines.append(NOTES_END)
    return "".join(lines)


def replace_block(text, begin, end, body):
    start = text.index(begin)
    stop = text.index(end) + len(end)
    return text[:start] + body + text[stop:]


def rewrite(text, entries, shelf, total, features):
    text = replace_block(text, SEED_BEGIN, SEED_END, seed_block(entries))
    text = replace_block(text, SHELF_BEGIN, SHELF_END, shelf_block(shelf, total))
    text = replace_block(text, NOTES_BEGIN, NOTES_END, notes_block(features))

    # Not prose, and not claims: values the page recomputes from live data on
    # load. They only have to be right for the moment before the script runs -
    # and for whoever is reading with JavaScript off.
    chromium = [release[0] for release in shelf.get("chromium") or []]
    if chromium:
        text = re.sub(r'aria-valuemax="\d+"',
                      'aria-valuemax="%d"' % (len(chromium) - 1), text)
        if STATIC_MILESTONE in chromium:
            text = re.sub(r'aria-valuenow="\d+"',
                          'aria-valuenow="%d"' % chromium.index(STATIC_MILESTONE),
                          text)

    # The four windows in the hero name the newest build of each engine. The page
    # rewrites them on load, but only these strings are there before it runs -
    # and for anyone reading with JavaScript off, they are all there ever is.
    windows = []
    for element, engine, name in (("mockVer", "chromium", "Chromium"),
                                  ("mockFirefox", "firefox", "Firefox"),
                                  ("mockEdge", "edge", "Edge"),
                                  ("mockWebkit", "webkit", "WebKit")):
        if shelf.get(engine):
            windows.append((element, name, shelf[engine][-1][1]))
    for element, name, version in windows:
        text = re.sub(r'(id="{}"[^>]*>){}[^<]*'.format(element, name),
                      lambda m, label="{} {}".format(name, version):
                          m.group(1) + label, text)
    return text


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="report drift, do not write")
    args = parser.parse_args()

    rows, builds, shelf, total = read_catalog()
    entries = seed_entries(rows, builds)
    if not entries:
        print("catalog.tsv has no usable rows", file=sys.stderr)
        return 1
    # An engine with no rows at all means discover.py has never run for it, or
    # ran and could not reach the vendor, or something upstream ate the S block.
    # Emptying its tab on the page would read as "this engine is gone" rather
    # than "nobody asked recently", so this stops rather than writing.
    #
    # It used to print this and write anyway. On 2026-08-31 refresh-catalog.py
    # rewrote catalog.tsv without the S rows, this ran next in the same workflow,
    # said its piece into a log nobody reads and published a page with an empty
    # shelf for all four engines and a hero counting zero versions. A warning is
    # not a guard when the caller is a cron job.
    empty = [e for e in SHELF_ENGINES if not shelf.get(e)]
    if empty:
        print("no shelf rows for %s - run tools/discover.py --write; "
              "refusing to write an empty shelf to %s"
              % (", ".join(empty), PAGE), file=sys.stderr)
        return 1
    features = read_features(shelf, entries)

    current = open(PAGE, encoding="utf-8").read()
    updated = rewrite(current, entries, shelf, total, features)

    if args.check:
        if current == updated:
            print("docs/index.html is up to date")
            return 0
        print("docs/index.html is behind catalog.tsv", file=sys.stderr)
        return 1
    if current == updated:
        print("docs/index.html already matches catalog.tsv")
        return 0
    with open(PAGE, "w", encoding="utf-8") as handle:
        handle.write(updated)
    print("wrote %s: %d releases over %d engines, %d with a changelog"
          % (PAGE, total, len(SHELF_ENGINES), len(features)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
